// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type Chunk struct {
	ID          int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DocumentID  int64
	StartOffset int64
	EndOffset   interface{}
	Content     sql.NullString
	Context     sql.NullString
}

type Conversation struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Document struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
	Filepath  string
	Filetype  string
	Filesize  int64
}

type Index struct {
	ID          int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        string
	Description sql.NullString
}

type Message struct {
	ID             int64
	ConversationID int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Ipv4Addr       string
	UserAgent      string
	Content        sql.NullString
}
