// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type Chunk struct {
	ID          int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DocumentID  int64
	StartOffset sql.NullInt64
	EndOffset   sql.NullInt64
	Content     string
	Context     string
	IndexingID  string
}

type Conversation struct {
	ID        int64
	SessionID string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Document struct {
	ID         int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
	IndexID    int64
	Filepath   string
	Filetype   string
	Filesize   int64
	Filesha256 string
}

type Index struct {
	ID          int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        string
	Description sql.NullString
	Path        string
}

type Message struct {
	ID             int64
	ConversationID string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Ipv4Addr       sql.NullString
	UserAgent      sql.NullString
	Content        string
	Role           string
}
